import { getBrandLogoUrl, getBrandName, getBrandPrimaryColor } from '../utils/runtimeConfig';

/**
 * Build a per-user completion certificate email (sent to the employee)
 */
export function buildUserCompletionCertificate(opts: {
  appUrl: string;
  batchName: string;
  userEmail: string;
  userName?: string;
  completedOn?: string;
  documents?: string[];
  department?: string;
  jobTitle?: string;
  location?: string;
  businessName?: string;
  primaryGroup?: string;
  verifyUrl?: string;
  certificateId?: string;
  includeAttachment?: boolean;
}): { subject: string; bodyHtml: string } {
  const certMode = opts.includeAttachment !== false;
  const brand = getBrandName();
  const logo = getBrandLogoUrl();
  const primary = getBrandPrimaryColor();
  const subject = certMode
    ? `Completion Certificate: ${opts.batchName}`
    : `Acknowledgement Completed: ${opts.batchName}`;
  const docCount = (opts.documents || []).length;
  const docsHtml = (opts.documents && opts.documents.length > 0)
    ? `<ol style="margin:12px 0 0 22px; color:#0f172a">${opts.documents.map(t => `<li>${String(t || 'Document')}</li>`).join('')}</ol>`
    : '<div style="color:#667085">No document titles available.</div>';
  const completedText = new Date(opts.completedOn || new Date().toISOString()).toLocaleString();
  const infoRows = renderCertificateInfoRows({
    department: opts.department,
    jobTitle: opts.jobTitle,
    location: opts.location,
    businessName: opts.businessName,
    primaryGroup: opts.primaryGroup
  }, completedText, docCount);
  const verifyHtml = certMode ? renderVerifySection(opts.verifyUrl, primary) : '';
  const certIdHtml = certMode && opts.certificateId ? `<div style="margin:8px 0 12px 0;color:#555;font-size:12px"><strong>Certificate ID:</strong> ${opts.certificateId}</div>` : '';
  const attachmentNote = certMode
    ? `<p style="margin:12px 0 0 0;color:#666;font-size:12px">Your completion certificate PDF is attached. You can always access the documents again from the portal.</p>`
    : '';
  const introCopy = certMode
    ? `This certifies that <strong>${opts.userName || opts.userEmail}</strong> completed all required acknowledgements for <strong>${opts.batchName}</strong>.`
    : `<strong>${opts.userName || opts.userEmail}</strong> completed all required acknowledgements for <strong>${opts.batchName}</strong>.`;
  const badgeLabel = certMode ? 'CERTIFICATE' : 'COMPLETED';
  const heading = certMode ? 'Completion Certificate' : 'Acknowledgement Completed';
  const footerCopy = certMode
    ? `This certificate was generated by ${brand}. If you did not complete this acknowledgement, contact HR immediately.`
    : `This acknowledgement was recorded by ${brand}. If you did not complete this, contact HR immediately.`;
  const bodyHtml = `<div style="background:#f7f8fa;padding:24px"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:720px;margin:0 auto;background:#ffffff;border:1px solid #e9ecef;border-radius:10px;overflow:hidden"><tr><td style="padding:16px 20px;border-bottom:1px solid #e9ecef;background:${primary};color:white"><div style="display:flex;align-items:center;gap:12px">${logo ? `<img src="${logo}" alt="${brand}" style="height:28px;display:block;border:0"/>` : ''}<strong style="font-family:Segoe UI,Tahoma,Arial,sans-serif;font-size:16px;line-height:1">${brand}</strong></div></td></tr><tr><td style="padding:20px;font-family:Segoe UI,Tahoma,Arial,sans-serif;color:#111"><div style="display:flex;align-items:center;gap:10px;margin-bottom:8px"><span style="display:inline-block;background:${primary};color:#fff;font-weight:700;border-radius:999px;padding:6px 12px;font-size:12px;letter-spacing:.3px">${badgeLabel}</span><span style="color:${completedText ? '#667085' : '#667085'};font-size:12px">${completedText}</span></div><h2 style="margin:0 0 12px 0;font-size:18px;color:#111">${heading}</h2><p style="margin:0 0 12px 0;color:#333">${introCopy}</p>${certIdHtml}<table role="presentation" cellpadding="0" cellspacing="0" style="width:100%;margin:8px 0 16px 0;color:#333">${infoRows}</table><h3 style="margin:12px 0 8px 0;font-size:14px;color:#111">Documents Acknowledged</h3>${docsHtml}${attachmentNote}<p style="margin:16px 0 0 0"><a href="${opts.appUrl}" target="_blank" rel="noopener" style="display:inline-block;background:${primary};color:#fff;text-decoration:none;padding:10px 14px;border-radius:8px;font-weight:700">Open Acknowledgement Portal</a></p>${verifyHtml}</td></tr><tr><td style="padding:16px 20px;border-top:1px solid #e9ecef;background:#fafbfc;color:#666;font-family:Segoe UI,Tahoma,Arial,sans-serif;font-size:12px"><div>${footerCopy}</div></td></tr></table></div>`;
  return { subject, bodyHtml };
}

function renderCertificateInfoRows(
  o: { department?: string; jobTitle?: string; location?: string; businessName?: string; primaryGroup?: string },
  completedText: string,
  docCount: number
): string {
  const rows: string[] = [];
  if (o.department) rows.push(`<tr><td style="padding:4px 8px 4px 0;color:#666;white-space:nowrap">Department:</td><td style="padding:4px 0"><strong>${o.department}</strong></td></tr>`);
  if (o.jobTitle) rows.push(`<tr><td style="padding:4px 8px 4px 0;color:#666;white-space:nowrap">Job title:</td><td style="padding:4px 0"><strong>${o.jobTitle}</strong></td></tr>`);
  if (o.location) rows.push(`<tr><td style="padding:4px 8px 4px 0;color:#666;white-space:nowrap">Location:</td><td style="padding:4px 0"><strong>${o.location}</strong></td></tr>`);
  if (o.businessName) rows.push(`<tr><td style="padding:4px 8px 4px 0;color:#666;white-space:nowrap">Business:</td><td style="padding:4px 0"><strong>${o.businessName}</strong></td></tr>`);
  if (o.primaryGroup) rows.push(`<tr><td style="padding:4px 8px 4px 0;color:#666;white-space:nowrap">Primary group:</td><td style="padding:4px 0"><strong>${o.primaryGroup}</strong></td></tr>`);
  rows.push(`<tr><td style="padding:4px 8px 4px 0;color:#666;white-space:nowrap">Completed on:</td><td style="padding:4px 0"><strong>${completedText}</strong></td></tr>`);
  rows.push(`<tr><td style="padding:4px 8px 4px 0;color:#666;white-space:nowrap">Documents:</td><td style="padding:4px 0"><strong>${docCount}</strong></td></tr>`);
  return rows.join('');
}

function renderVerifySection(verifyUrl: string | undefined, primary: string): string {
  if (!verifyUrl) return '';
  return `<p style="margin:12px 0 0 0"><a href="${verifyUrl}" target="_blank" rel="noopener" style="display:inline-block;border:1px solid ${primary};color:${primary};text-decoration:none;padding:9px 13px;border-radius:8px;font-weight:700">Verify Certificate</a></p><p style="margin:8px 0 0 0;color:#666;font-size:12px">If the button doesn’t work, copy and paste this link:<br/><span style="word-break:break-all;color:#555">${verifyUrl}</span></p>`;
}
